### ISSUE TITLE
Linter silently fails on null value error

### ISSUE THREAD

**Issue by wolfkarl** [awslabs/aws-cfn-lint-atom#32]
```yml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  # Unsupported Type "AWS::EC2::Instance1"
  MyEC2Instance1:
    Type: "AWS::EC2::Instance1"
      Metadata:
```

This minimal config makes the linter fail silently -- no errors are shown.

Running `cfn-lint` manually returns `E0000 Null value at line [...]`
